#!/bin/bash

BIN=./vlc.exe
SAMPLERATE=44100
BITRATE=128
if [ -z $1 ]; then
        echo "Usage: $0 <input file> <outputfile> <start seconds> <end seconds>"
        exit 1
fi
if [ -z $2 ]; then
        OUTFILE=~/output.mp3
else
        OUTFILE=~/$2
fi
if [ -z $3 ]; then
        STARTTIME="--start-time=$3"
else
        STARTTIME=""
fi
if [ -z $4 ]; then
        STOPTIME="--end-time=$4"
else
        STOPTIME=""
fi
TRANSCODEMP3="#transcode{acodec=mp3,ab=$BITRATE,channels=2,samplerate=$SAMPLERATE}:std{access=file,mux=raw,dst=$OUTFILE}"
PARAMS="-I dummy $STARTTIME $ENDTIME --no-sout-video --sout-audio --no-sout-rtp-sap --no-sout-standard-sap --ttl=1 --sout-keep --sout $TRANSCODEMP3 $1 vlc://quit"
echo "$BIN $PARAMS"
$BIN $PARAMS
